site_name: 'CiviCRM User Guide'
site_url: https://docs.civicrm.org/user/en/stable/
repo_url: https://github.com/civicrm/civicrm-user-guide
edit_uri: edit/4.6/docs/
site_description: 'A guide for CiviCRM users.'
site_author: 'The CiviCRM community'
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

pages:
- Home: 'index.md'
- Introduction:
    - 'What is CiviCRM?': 'introduction/what-is-civicrm.md'
    - 'Real world examples': 'introduction/real-world-examples.md'
    - 'Components': 'introduction/components.md'
    - 'Extensions': 'introduction/extensions.md'
    - 'Who is CiviCRM?': 'introduction/who-is-civicrm.md'
- Getting prepared:
    - 'Is CiviCRM for You?': 'getting-prepared/is-civicrm-for-you.md'
    - 'Identifying your needs': 'getting-prepared/identifying-your-needs.md'
    - 'Test it out': 'getting-prepared/test-it-out.md'
    - 'Hosting': 'getting-prepared/hosting.md'
    - 'Transitioning to CiviCRM': 'getting-prepared/transitioning-to-civicrm.md'
- Initial set up:
    - 'Installation and basic set-up': 'initial-set-up/installation-and-basic-set-up.md'
    - 'Scheduled jobs': 'initial-set-up/scheduled-jobs.md'
    - 'Customizing the user interface': 'initial-set-up/customizing-the-user-interface.md'
    - 'Permissions and access control': 'initial-set-up/permissions-and-access-control.md'
    - 'Security': 'initial-set-up/security.md'
- Advanced configuration:
    - 'Email System Configuration': 'advanced-configuration/email-system-configuration.md'
    - 'Logging': 'advanced-configuration/logging.md'
- The user interface:
    - 'Menu, dashboard and dashlets': 'the-user-interface/menu-dashboard-and-dashlets.md'
    - 'Searching': 'the-user-interface/searching.md'
    - 'Undelete': 'the-user-interface/undelete.md'
- Organising your data:
    - 'Overview': 'organising-your-data/overview.md'
    - 'Mapping your data': 'organising-your-data/mapping-your-data.md'
    - 'Contacts': 'organising-your-data/contacts.md'
    - 'Groups and tags': 'organising-your-data/groups-and-tags.md'
    - 'Smart groups': 'organising-your-data/smart-groups.md'
    - 'Activities': 'organising-your-data/activities.md'
    - 'Relationships': 'organising-your-data/relationships.md'
    - 'Creating custom fields': 'organising-your-data/creating-custom-fields.md'
    - 'Profiles': 'organising-your-data/profiles.md'
- Common workflows:
    - 'Importing data into CiviCRM': 'common-workflows/importing-data-into-civicrm.md'
    - 'Exporting your contacts': 'common-workflows/exporting-your-contacts.md'
    - 'Deduping and merging': 'common-workflows/deduping-and-merging.md'
    - 'Tokens and mail merge': 'common-workflows/tokens-and-mail-merge.md'
    - 'Postal mail communications': 'common-workflows/postal-mail-communications.md'
    - 'Automating tasks': 'common-workflows/automating-tasks.md'
- Contributions:
    - 'What is CiviContribute?': 'contributions/what-is-civicontribute.md'
    - 'What you need to know': 'contributions/what-you-need-to-know.md'
    - 'Online contributions': 'contributions/online-contributions.md'
    - 'Manual entry of contributions': 'contributions/manual-entry-of-contributions.md'
    - 'Finding and viewing contributions': 'contributions/finding-and-viewing-contributions.md'
    - 'Manual receipts and thank-you letters': 'contributions/manual-receipts-and-thank-yous.md'
    - 'Reports and analysis': 'contributions/reports-and-analysis.md'
    - 'Soft credits': 'contributions/soft-credits.md'
    - 'Personal campaign pages': 'contributions/personal-campaign-pages.md'
    - 'Accounting integration': 'contributions/accounting-integration.md'
    - 'Payment processors': 'contributions/payment-processors.md'
    - 'Invoicing': 'contributions/invoicing.md'
    - 'Sales tax and VAT': 'contributions/sales-tax-and-vat.md'
    - 'Premiums': 'contributions/premiums.md'
    - 'Widgets': 'contributions/widgets.md'
- Pledges:
    - 'What is CiviPledge?': 'pledges/what-is-civipledge.md'
    - 'What you need to know': 'pledges/what-you-need-to-know.md'
    - 'Set-up': 'pledges/set-up.md'
    - 'Everyday tasks': 'pledges/everyday-tasks.md'
    - 'Pledges reports and analysis': 'pledges/pledges-reports-and-analysis.md'
- Events:
    - 'What is CiviEvent?': 'events/what-is-civievent.md'
    - 'Event planning and management': 'events/event-planning-and-management.md'
    - 'Creating an event': 'events/creating-an-event.md'
    - 'Online event registration': 'events/online-event-registration.md'
    - 'Integrating events with your website': 'events/integrating-events-with-your-website.md'
    - 'Manual event registration': 'events/manual-event-registration.md'
    - 'Keeping track of events and participants': 'events/keeping-track-of-events-and-participants.md'
    - 'Complex event fees': 'events/complex-event-fees.md'
    - 'Event templates': 'events/event-templates.md'
    - 'Reports': 'events/reports.md'
    - 'Custom data for events': 'events/custom-data-for-events.md'
    - 'Repeating Events': 'events/repeating-events.md'
- Membership:
    - 'What is CiviMember': 'membership/what-is-civimember.md'
    - 'Defining memberships': 'membership/defining-memberships.md'
    - 'Online membership sign up': 'membership/online-membership-sign-up.md'
    - 'Manual entry of memberships': 'membership/manual-entry-of-memberships.md'
    - 'Membership price sets': 'membership/membership-price-sets.md'
    - 'Finding and viewing memberships': 'membership/finding-and-viewing-memberships.md'
    - 'Membership reports': 'membership/membership-reports.md'
    - 'Renewals': 'membership/renewals.md'
    - 'Cancelling and expiring memberships': 'membership/cancelling-and-expiring-memberships.md'
    - 'Making member only websites': 'membership/making-member-only-websites.md'
- Email:
    - 'What is CiviMail?': 'email/what-is-civimail.md'
    - 'What you need to know': 'email/what-you-need-to-know.md'
    - 'Set-up': 'email/set-up.md'
    - 'Maintaining healthy email lists': 'email/maintaining-healthy-email-lists.md'
    - 'Some everyday tasks': 'email/some-everyday-tasks.md'
    - 'Mass mailings using CiviMail': 'email/mass-mailings-using-civimail.md'
    - 'Using tokens in emails': 'email/using-tokens-in-emails.md'
    - 'Reports and analysis': 'email/reports-and-analysis.md'
    - 'Scheduled reminders': 'email/scheduled-reminders.md'
    - 'CiviMail A/B testing': 'email/civimail-ab-testing.md'
- SMS (text messaging):
    - 'What is SMS?': 'sms-text-messaging/what-is-sms.md'
    - 'Set-up': 'sms-text-messaging/set-up.md'
    - 'Everyday tasks': 'sms-text-messaging/everyday-tasks.md'
    - 'SMS Reports and analysis': 'sms-text-messaging/reports-and-analysis-sms.md'
- Reporting:
    - 'What is CiviReport?': 'reporting/what-is-civireport.md'
    - 'What you need to know': 'reporting/what-you-need-to-know.md'
    - 'Set-up': 'reporting/set-up.md'
    - 'Everyday tasks': 'reporting/everyday-tasks.md'
- Case management:
    - 'What is CiviCase?': 'case-management/what-is-civicase.md'
    - 'What you need to know': 'case-management/what-you-need-to-know.md'
    - 'Set-up': 'case-management/set-up.md'
    - 'Everyday tasks': 'case-management/everyday-tasks.md'
    - 'Reports and analysis': 'case-management/reports-and-analysis.md'
- Campaign:
    - 'What is CiviCampaign?': 'campaign/what-is-civicampaign.md'
    - 'What you need to know': 'campaign/what-you-need-to-know.md'
    - 'Set-up': 'campaign/set-up.md'
    - 'Everyday tasks': 'campaign/everyday-tasks.md'
    - 'Reports and analysis': 'campaign/reports-and-analysis.md'
- Survey:
    - 'What is CiviSurvey?': 'survey/what-is-civisurvey.md'
    - 'What you need to know': 'survey/what-you-need-to-know.md'
    - 'Set-up': 'survey/set-up.md'
    - 'Everyday tasks': 'survey/everyday-tasks.md'
    - 'Reports and analysis': 'survey/reports-and-analysis.md'
    - 'What is GOTV (Voter Tracking)?': 'survey/what-is-gotv-voter-tracking.md'
- Petition:
    - 'What is CiviPetition?': 'petition/what-is-civipetition.md'
    - 'What you need to know': 'petition/what-you-need-to-know.md'
    - 'Set-up': 'petition/set-up.md'
    - 'Everyday tasks': 'petition/everyday-tasks.md'
    - 'Reports and analysis': 'petition/reports-and-analysis.md'
- Civic Engagement:
    - 'What is CiviEngage?': 'civic-engagement/what-is-civiengage.md'
    - 'What you need to know': 'civic-engagement/what-you-need-to-know.md'
    - 'Set-up': 'civic-engagement/set-up.md'
    - 'Everyday tasks': 'civic-engagement/everyday-tasks.md'
    - 'Reports and analysis': 'civic-engagement/reports-and-analysis.md'
- Grants:
    - 'What is CiviGrant?': 'grants/what-is-civigrant.md'
    - 'What you need to know': 'grants/what-you-need-to-know.md'
    - 'Set-up': 'grants/set-up.md'
    - 'Everyday tasks': 'grants/every-day-tasks.md'
    - 'Reports and analyis': 'grants/reports-and-analysis.md'
- Website integration:
    - 'Choosing your CMS': 'website-integration/choosing-your-cms.md'
    - 'Integrating with Drupal': 'website-integration/integrating-with-drupal.md'
    - 'Integrating with WordPress': 'website-integration/integrating-with-wordpress.md'
    - 'Integrating with Joomla': 'website-integration/integrating-with-joomla.md'
- The CiviCRM Community:
    - 'The CiviCRM Community': 'the-civicrm-community/the-civicrm-community.md'
    - 'Bug Reporting': 'the-civicrm-community/bug-reporting.md'
    - 'Localising CiviCRM': 'the-civicrm-community/localising-civicrm.md'
    - 'Contributing to this manual': 'the-civicrm-community/contributing-to-this-manual.md'
- Appendices:
    - 'History of this book': 'appendices/history-of-this-book.md'
    - 'Free Software?': 'appendices/free-software.md'
    - 'Glossary': 'appendices/glossary.md'
    - 'Credits': 'appendices/credits.md'
